### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by teran-mckinney** [aforensics/HiddenVM#2]
Thought this was an interesting project. I've done some similar things with [Vagabond Workstation](https://vagabondworkstation.github.io/) and wanted to mention it in case you hadn't seen it. I'm doing Torified VMs there as well.

**Comment by animik** [comment]
Thank you! I'll take a look at your documentation soon. If you have any useful ideas, or even code you wanted to contribute, feel free to discuss in our [subreddit](https://www.reddit.com/r/HiddenVM/) or make pull requests directly. We're still in the process of setting everything up as you can probably see.
