### ISSUE TITLE
TAILS (5.0) is not running HiddenVM from my Veracrypt Hidden Volume !!!

### ISSUE THREAD

**Issue by blackpeoplemeet** [aforensics/HiddenVM#23]
Daddy PLEASE help me like i literally cant with this shit I'm just so fuucking tirrrrred DX

I have a big hunch that this just has something to do with the TAILS system but I figured you would know something about it too since you made the shit FOR the shit and so you would KNOW if your shit doesnt work on the shit! (like seriously, how the fuck do you not see this shit coming!??)

### **Procedure to replicate the contingency:**

1. Follow all the steps in the Installation Guide
2. Try to run the newly installed appimage from your hidden VeraCrypt folder
3. get this prompt followed by this STUPID fucking error message!!!

""X GB Volume" contains software intended to be automatically started. Would you like to run it?
If you don't trust this location or aren't sure, press Cancel." 

Run >> "Oops! There was a problem running this software. Unable to locate the program" (like even the way it says it to me is so fucking annoying ("Oops!" ??) that I punched the shit out of my monitor and now it blinks red and white sometimes, but that's another issue for another nerd forum)

PLEASE tell me you know something about this PLEASE

This is like a major blue ball, you promised maximum anonymity and security, you fucking promised !!! This is major orgasm denial, it should be ILLEGAL.

Thanks for reading, and I appreciate all the work that you do! ^^

Sincerely,
blackpeoplemeet <3

**Comment by blackpeoplemeet** [comment]
Also, please ignore my bitch-speak, I'm currently OD'ing on a mix of percs and modified fents which is affecting my mood (don't worry, I can take it.)
Granted, I am NOT too high to see this shit, so fucking fix it!

**Comment by aforensics** [comment]
I have a feeling you might be running other Tails persistent software in addition to HiddenVM (which affects the ability to run .appimage files), or something else. Try installing HVM on a completely untouched Tails environment - the latest Tails version (5.1 currently).

**Comment by aforensics** [comment]
Closing ticket to clean up.
