### ISSUE TITLE
Whonix Workstation graphic artifacts Tor Browser crash

### ISSUE THREAD

**Issue by Random-Anon69** [aforensics/HiddenVM#25]
Since I had update Tails to v.5.1.1 and HiddenVM to the version 1.26.1, when I open my Whonix Workstation VM and goes on Tor Browser I frequently saw weird color graphic artifacts on a part of the window. It appear and disappear randomly as I used the the browser. When I used the browser to open website like I did normally it randomly crash (It seam to happen more frequently as I open new tabs with new websites.)
Sincerely the crash is so frequent that it just make it impossible to browse on internet on Whonix.

I never had that issue before the update and I tried on 2 different version of Whonix Workstation and both have the same exact problem, so I'm sure that it is not the machine who is the problem.

I have tried with 3D acceleration enabled and disabled and in both case the same issue.

For what I see, the visual glitch happen with other app, like the file browser, specially when I move the window, but doesn't seam to crash like Tor Browser do all the time. I can still watch a video on VLC without issue or continuous visual issue, so I don't really know what's caused that weird issue exactly.

If I manage to find something I will reply at that issue and give you more information.

**Comment by Random-Anon69** [comment]
After some time of usage the whole graphical interface crashed, I saw for second or 2 only Terminal lines and are send back to login screen. Once I log back in, none of the application I was running are open. That's appens 3 or 4 time while I was using the Virtual PC with other applications and I didn't used it much compare of what I do in general, just 1 or 2 applications open that's all.

So today I'm back using Tails 5.1 with HiddenVM 1.26 and everything works fine until now on the same VM. I had tryied to run HiddenVM 1.26 on Tails 5.1 before starting using back an older version of Tails, but it doesn't work at all, the installation crash all the time, so I had sadly no other choice. I really hope things get fixed soon, so I can start using back the latest version of both.

**Comment by AlCervik** [comment]
@Random-Anon69,

If it's any consolation, I have the same issue, and have since Tails 5.1.1 and HiddenVM 1.26 were released. Tails 5.2 and HVM 1.27 didn't fix the issue.

At this point, the whole Whonix via Tails and HiddenVM is unstable at best, and useless at worst. My experience is, "useless."

I guess we wait for the next update to see if it resolves. I don't have high hopes at this point, though.

**Comment by Random-Anon69** [comment]
@AlCervik,
Thank you to confirm that I'm not alone to have that issue.
I just update to Tails 5.2 to test with HVM 1.27 and I also have the exact same issue. HiddenVM is totally unusable right now until that issue is fixed on newer version of Tails, and continuing using old version of Tail is not really a good solution, but I don't have much choice.

I hope the dev manage to find a solution fast to that problem. If you need some informations @aforensics to manage to fixed that issue you can ask and I will try to provide you those for you.

**Comment by AlCervik** [comment]
@Random-Anon69 

Have you seen any other threads discussing this on any other forums such as Whonix, Tor Browser forum, or Tails forum? If so and you don't mind, please link them here. 

This is the only thread I've seen discussing this exact issue.

**Comment by Random-Anon69** [comment]
@AlCervik

I didn't see any threads about that issue elsewhere either, but the whonix team dev doesn't support HiddenVM and doesn't want to give any effort to help on the dev of that tool. They have decide instead to work on their own project called Whonix-Host which is a Live-CD / USB operating system to start both Whonix VMs. The project is still in development and they ask to not used it as user since some core feature is not ready yet.

The Whonix dev have refused to help ApexMan (On tail forum) or IncognitoIceman (On Github) for his HiddenVM fork using KVM instead of VirtualBox. So I don't they they will give some real help for an issue who is possibly due to incompatibility with VirtualBox with some package (or drivers maybe) of the latest Tails version.  (You can see here: https://www.whonix.org/wiki/Declined and here: https://forums.whonix.org/t/hiddenvm-kvm-version/14155/4) their refusal to support the project.

On the Tails side, since it is not a problem of the OS by itself, who work great without any issue by itself, I don't think they will want to put some efforts to fixed an issue tier product software. As long as their OS work great and have no crash or problem directly, I don't see why they would try to help, but it still more likely to happen than the Whonix Team. One thing I didn't try is to install another OS than Whonix on HiddenVM and see if there have the same problem.

**Comment by anon-1231** [comment]
Also possibly related (https://forums.virtualbox.org/viewtopic.php?f=7&t=106436#p520296). 

Since Tails 5.1.1 updated the kernel to 5.10.120, our hope might be to wait for Virtualbox 6.1.35.

**Comment by Random-Anon69** [comment]
@anon-1231 

Thank you very much for those information. This totally make sens, the problem seam to be a common one between the Linux kernel and VirtualBox. If the information is true, VirtualBox 6.1.35 should fixed that issue! I really hope it is the case and hope that version will be availiable in stable version soon!

**Comment by AlCervik** [comment]
A VBox upgrade even with the latest 6.1.34.150xxx update should fix it.

@aforensics , is there any way we can get an incremental update with the latest VBox version?

**Comment by Random-Anon69** [comment]
@anon-1231

@AlCervik, For what I see on the source code, HiddenVM automatically download the latest version availiable on the VirtualBox repository for debian Bullseye. Unstable version of VirtualBox are not on the repository, so the only way to make it download and install the latest unstable version would be to change completly the way HiddenVM download and install the package, to install by source-codes compilation, which is possible but more complex and will not be able to go download the last version when it is availiable.

But, I also just check on the repository and it seam like the version 6.1.36 142142 just been release not long ago, so if you start Tails and setup Hidden-VM today, it might download the latest version. But it is important to note that HiddenVM automatically do a 'apt-get update' only every 7 days, so if the last one have been done less than 7 days ago he might still install the previous version.

To force installing the latest update during your installation I think deleting the file 'HiddenVM/cache/last-apt-update-for-vbox'  in your Hidden Volume should work.

I didn't try yet since I just saw that the update is out after installing HiddenVM, so I can't confirm at 100% that the problem is fixed now, I will restart and test it.

**Comment by AlCervik** [comment]
@anon-1231 @Random-Anon69 @aforensics 

> To force installing the latest update during your installation I think deleting the file 'HiddenVM/cache/last-apt-update-for-vbox' in your Hidden Volume should work.
> 

This 100% resolved the issue for me. It does force the download, but it's important to point out that Tails must be connected to Tor first.

@Random-Anon69 have you tried this yet?

**Comment by AlCervik** [comment]
@anon-1231 

Frikkin' genious, man. Here, have a few imaginary internet points. lol

**Comment by Random-Anon69** [comment]
I can confirm too, on my side everything works #1 with Tails 5.2, so the problem should be fixed. I think we can close the issue now...
