### ISSUE TITLE
Mouse randomly stop working on VirtualBox, while using my VM

### ISSUE THREAD

**Issue by Random-Anon69** [aforensics/HiddenVM#29]
Since the last update, using HiddenVM 1.33 and Tails 5.8, when using my VM, sometime the mouse randomly stop working on VirtualBox. The problem seem to happens really frequently, but I cannot find what action I do exactly who caused that issue to happens.

While the mouse stop working, the keyboard continue to work in the VM and the mouse is not frozen, but I cannot interact with anything on the entire VirtualBox (HiddenVM) app. The only way to fixed that issue is to close my VM. Once my VM is closed, the mouse start working again without issue and I can start back the VM and work on it for few minutes until the problem start again.

After looking on internet, it seem to be an issue between VitualBox and Wayland, but I actually can't find any real fixed to that issue currently, so I was wondering if there have a little something I can do, maybe a command or something I can do differently who would allow me to fixed temporarily that issue or to start the HiddenVM in a way who doesn't have that issue maybe?

If that can help, I run Whonix Workstation + Whonix Gateway VM on HiddenVM, and my Workstation is usually in full-screen.

Thank you

**Comment by aforensics** [comment]
I think this is a complex issue affecting Xorg as well as Wayland. (I often have experienced this well before Tails went to Wayland.) It is best to ask on VirtualBox forums in the Linux host section. It would be not something HiddenVM itself can fix. It may also only affect certain hardware and video drivers in the host may play a role.
