### ISSUE TITLE
Installation always times out w/ 1.40 version

### ISSUE THREAD

**Issue by bedrynski** [aforensics/HiddenVM#34]
I'm at a loss. Installation of HiddenVM v1.40 never completes. Tried multiple networks, wired, wireless, VPN, etc. Two different PCs. Different days. Never had this issue with prior versions. Running bootstrap.sh always ends with "Connection timed out"

running sudo apt-get update on tails prior does not change the result
[HiddenVM.log](https://github.com/aforensics/HiddenVM/files/12139771/HiddenVM.log)

**Comment by llamabyte** [comment]
same
[HiddenVM.log](https://github.com/aforensics/HiddenVM/files/12246592/HiddenVM.log)

**Comment by aforensics** [comment]
This is always an issue with Tor itself, it's frustrating. (Whonix also sometimes does this.) It's the Tor circuit (e.g. the exit node), that's failing. Close off HVM and try again (you can also test if web is loading OK in Tails Tor Browser which seems to 'wake up' the circuit..sometimes). Usually it works the second time right away. If it's really bad, the whole Tor circuit needs a fuller reset, and you may need to restart Tails itself as the simplest way. (That has only ever been needed a few times in my experience.) Or if you have time, wait a little while to see if a new (auto cycling) circuit works again. Frustrating, but worth living with. I've added this solution to README FAQ.
