### ISSUE TITLE
Installation aborted because /media/amnesia did not exist

### ISSUE THREAD

**Issue by basnappl** [aforensics/HiddenVM#4]
When I executed the appimage, I got an error because `/media/amnesia` did not exist.  I am not sure why.  I am using a TAILS USB that has a persistent volume, although I did not unlock the persistent volume this time (as per the README).  I did `sudo mkdir /media/amnesia` and re-ran the appimage and it worked fine.  So, maybe throw an if-statement in there and create the directory if it doesn't already exist?

**Comment by aforensics** [comment]
Thank you.

A (bad) assumption had been made that the user would have mounted something before running HiddenVM (and thus /media/amnesia/ would already exist). But obviously that's not always the case. This is now fixed in v1.2.5.
